branches:
  - main
preset: "conventionalcommits"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/npm", {
      "pkgRoot": "packages/vana-sdk"
    }]
  - ["@semantic-release/git", {
      "assets": ["package.json", "package-lock.json", "packages/vana-sdk/package.json"],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }]
  - "@semantic-release/github"