branches:
  - main
preset: "conventionalcommits"
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - ["@semantic-release/npm", {
      "pkgRoot": "packages/vana-sdk"
    }]
  - "@semantic-release/github"