name: Generate and Deploy Documentation

on:
  push:
    branches: [ main, typedoc ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build SDK
      run: npm run build:sdk
      
    - name: Generate documentation
      run: npm run docs
      
    - name: Setup Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/typedoc'
      uses: actions/configure-pages@v5
      
    - name: Upload artifact
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/typedoc'
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs'
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/typedoc'
      id: deployment
      uses: actions/deploy-pages@v4